# Generated by Django 3.1.5 on 2021-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senddocs',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
