# Generated by Django 3.1.5 on 2021-02-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210127_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=250, verbose_name='Адрес многоквартирного дома')),
                ('company', models.CharField(max_length=250, verbose_name='Наименование/ ФИО лицензиата')),
                ('date_start', models.DateField(verbose_name='Дата начала полномочий по управлению домом')),
                ('date_end', models.DateField(verbose_name='Дата окончания полномочий по управлению домом')),
                ('reason_to_exclude', models.CharField(max_length=250, verbose_name='Основание исключения')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('date_changed', models.DateField(verbose_name='Дата последнего изменения')),
            ],
        ),
    ]
