# Generated by Django 3.1.5 on 2021-02-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_licenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senddocs',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='senddocs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='senddocs',
            name='salary',
        ),
    ]
