# Generated by Django 3.1.5 on 2021-02-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210210_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Дата окончания полномочий по управлению домом'),
        ),
        migrations.AlterField(
            model_name='license',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Дата начала полномочий по управлению домом'),
        ),
        migrations.AlterField(
            model_name='license',
            name='reason_to_exclude',
            field=models.CharField(max_length=250, null=True, verbose_name='Основание исключения'),
        ),
    ]
