# Generated by Django 3.1.5 on 2021-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20210210_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30, verbose_name='Событие')),
                ('home_address', models.CharField(max_length=250, verbose_name='Адрес многоквартирного дома')),
                ('prev_company', models.CharField(max_length=250, verbose_name='Наименование/ ФИО лицензиата')),
                ('prev_inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('prev_date_start', models.DateField(null=True, verbose_name='Дата начала полномочий по управлению домом')),
                ('prev_date_end', models.DateField(null=True, verbose_name='Дата окончания полномочий по управлению домом')),
                ('prev_reason_to_exclude', models.CharField(max_length=250, null=True, verbose_name='Основание исключения')),
                ('new_company', models.CharField(max_length=250, verbose_name='Наименование/ ФИО лицензиата')),
                ('new_inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('new_date_start', models.DateField(null=True, verbose_name='Дата начала полномочий по управлению домом')),
            ],
        ),
    ]
